apiVersion: automl.my.domain/v1
kind: Proxy
metadata:
  labels:
    app.kubernetes.io/name: proxy
    app.kubernetes.io/instance: proxy-sample
    app.kubernetes.io/part-of: ray-automl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ray-automl
  name: proxy-sample
  namespace: ray-automl-system
spec:
  startParams:
    grpc-port: "1234"
  deploySpec:
    selector:
      matchLabels:
        control-plane: controller-manager
        app.kubernetes.io/instance: proxy-sample
    replicas: 1
    template:
      spec:
        containers:
        - command:
          - /busybox/sh
          args:
          - sleep infinity
          image: gcr.io/distroless/static:debug
          imagePullPolicy: IfNotPresent
          name: proxy
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        terminationGracePeriodSeconds: 10
